name: CorvusTPA
version: '0.1.0'
main: de.emn4tor.CorvusTPA
api-version: '1.21'
commands:
  tpa:
    description: Request to teleport to another player
    usage: /tpa <player>
    permission: corvustpa.tpa
  tpaccept:
    description: Accept a teleport request
    usage: /tpaccept
    permission: corvustpa.tpaccept
  tpdeny:
    description: Deny a teleport request
    usage: /tpdeny
    permission: corvustpa.tpdeny
  tphere:
    description: Request a player to teleport to you
    usage: /tphere <player>
    permission: corvustpa.tphere
  tpcancel:
    description: Cancel a pending teleport request
    usage: /tpcancel
    permission: corvustpa.tpcancel

permissions:
  corvustpa.tpa:
    description: Allows the use of /tpa command
    default: true
  corvustpa.tpaccept:
    description: Allows the use of /tpaccept command
    default: true
  corvustpa.tpdeny:
    description: Allows the use of /tpdeny command
    default: true
  corvustpa.tphere:
    description: Allows the use of /tphere command
    default: true
  corvustpa.tpcancel:
    description: Allows the use of /tpcancel command
    default: true

